### ISSUE TITLE
not working here

### ISSUE THREAD

**Issue by Oonaganga** [HenningM/express-ws#22]
I've tried folding the example code into an instance of express that was created using express-generator. I don't ever get a connection happening from the client side, and a breakpoint set with node-inspector in the app.ws callback function never gets hit.

The startup code (./bin/www) created with express-generator does some things that may have not been anticipated? It basically requires app.js and sets up a listener on a port itself.

**Comment by Oonaganga** [comment]
Continuing to experiment, I successfully implemented a websocket server in Express using socket.io. I did have to import their client-side code into a web page in order to connect, however. The native browser WebSocket() function would not work. I tried connecting to an express-ws server using the socket.io webpage and that also failed.

Maybe a complete example would be helpful including a browser client and whatever is required to enable it.

**Comment by blloyd75** [comment]
You will either need to pass the http server to the express-ws initialization function, or call app.listen after initializing express-ws.

**Comment by Alvaroctal** [comment]
I tried as you say, but I'm unable to make to socket work with the library, if I have understood fine...

![captura de pantalla 2016-03-21 14 46 58](https://cloud.githubusercontent.com/assets/4562922/13920594/1f3f662c-ef74-11e5-85df-f8d04ac35a69.png)
the socket doesn't seems to be open... so if I place instead:

![captura de pantalla 2016-03-21 14 51 18](https://cloud.githubusercontent.com/assets/4562922/13920648/65fb12aa-ef74-11e5-9f30-1494bb390469.png)

if fails due to:
`throw new TypeError('listener must be a function');`

thanks in advance.

**Comment by almarkov** [comment]
from http://stackoverflow.com/questions/40362258/package-express-ws-doesnt-let-clients-connect
changes to app.js

```
var app = express();
var server = require('http').Server(app);
var expressWs = require('express-ws')(app,server);
...
...
//module.exports = app;
module.exports = {app: app,server: server};
```
changes to bin/www

```
//var app = require('../app');
var app = require('../app').app;
...
...
//var server = http.createServer(app);
var server = require('../app').server;
```

**Comment by VictorioBerra** [comment]
For the love of god please note this in the README and push to NPM so its in the README there too. @HenningM
