### ISSUE TITLE
How does this behave with routers?

### ISSUE THREAD

**Issue by nicola** [HenningM/express-ws#8]
Hey there,
awesome library that removes a lot of hassle, really!

I have this particular use case in which I am releasing a library which expose a Express router,
so here is the following use case:

```
var linkedDataProvider = require("./ldp")
var express = require("express")
var app = express();
app.use('/test', ldp({patch: true}));
```

Now, the implementation of ldp is as following:

```
module.exports = function(opts) {
  var router = new express.Router();
  [...]
  router.post("/", postOrPatch);
  router.delete("/", deleteObj);
  [...]
  return router;
}
```

Now, if I want to include

```
router.ws(''/", realTime);
```

How can make this happen?

My ideas are the following

- I require('express-ws')(router) ?
- I have express-ws outside my library, so if you need you can set extra property
- I have to have another function for creating ldp routes like `ldp(route)(app)`

Thanks a lot for your time

**Comment by GlitterCakes** [comment]
Being able to add web socket routes the same way we add any other route would really be great and it would help keep the code clean. I really hope this gets implemented.

**Comment by HenningM** [comment]
Hi,

First of all: I'm flattered that you find this library useful.

I also agree that the feature described here would be a very nice addition, so I'll have a look at it ASAP. Unfortunately it's not entirely straightforward to implement support for routers since they don't have any information on where they are mounted in the application. This means that we don't know which path to give the `WebSocketServer` when we run `router.ws('/socket', handler)`. The router could be mounted anywhere in the application.

I will try to come up with a (not too hacky) solution here though, and I'll keep you updated.

**Comment by nicola** [comment]
Hey @HenningM, thanks a lot, if you don't mind I might try to attempt that soon as well with a PR

**Comment by nicola** [comment]
any news?

**Comment by HenningM** [comment]
Hi again @nicola,

Unfortunately I still haven't had time to look into this yet myself, but I'll happily merge in any PR that seems to work well with the existing functionality.

I hope I'll be able to spend some hours working on this library soon, but the last few months have been quite busy, so at the moment I'm unable to give you a good ETA here.

**Comment by Prior99** [comment]
+1

**Comment by Nickoladze** [comment]
I'd love to see some work on this

**Comment by joepie91** [comment]
I've just rewritten `express-ws` to have support for Express Routers, including custom ones such as `express-promise-router` (without running afoul of #17). I will do some final testing tomorrow, and make a PR.

**Comment by nicola** [comment]
This is awesome, thanks! @joepie91 , @HenningM
